### ISSUE TITLE
Document in README how to test smtliblib on z3 output from the command line

### ISSUE THREAD

**Issue by bzorn** [dbarowy/smtliblib#1]
If z3 produces a sat result, it would be great to be able to run smtliblib from the command line and see the AST it produces from Z3.Parse.

The functionality is available in tests\debug_runner.ts but I'm not sure how to invoke it.

**Comment by dbarowy** [comment]
Done in 3bbe42d935ea2a6faf2f689310791751a6d69b03.  See the [README](https://github.com/dbarowy/smtliblib/blob/main/README.md).
